// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepPvtTracker.Infrastructure.Data;

#nullable disable

namespace SleepPvtTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SleepPvtTracker.Core.Entities.SleepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Bedtime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WakeUpTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SleepRecords");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Bedtime = new DateTime(2026, 6, 10, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "よく眠れた",
                            WakeUpTime = new DateTime(2026, 6, 11, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Bedtime = new DateTime(2026, 6, 12, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            Comments = "",
                            WakeUpTime = new DateTime(2026, 6, 12, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SleepPvtTracker.Core.Entities.SleepRecord", b =>
                {
                    b.OwnsOne("SleepPvtTracker.Core.ValueObjects.PvtResult", "PvtResult", b1 =>
                        {
                            b1.Property<Guid>("SleepRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PvtEndTime");

                            b1.Property<int>("ExtraFalseStarts")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PvtExtraFalseStarts");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PvtStartTime");

                            b1.HasKey("SleepRecordId");

                            b1.ToTable("SleepRecords");

                            b1.WithOwner()
                                .HasForeignKey("SleepRecordId");

                            b1.OwnsMany("SleepPvtTracker.Core.ValueObjects.PvtTrial", "Trials", b2 =>
                                {
                                    b2.Property<Guid>("PvtResultSleepRecordId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("ChacngedAt")
                                        .HasColumnType("INTEGER");

                                    b2.Property<long>("ClickedAt")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("PvtResultSleepRecordId", "Id");

                                    b2.ToTable("SleepRecordPvtTrials", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PvtResultSleepRecordId");
                                });

                            b1.Navigation("Trials");
                        });

                    b.OwnsOne("SleepPvtTracker.Core.ValueObjects.SubjectiveSleepiness", "Sleepiness", b1 =>
                        {
                            b1.Property<Guid>("SleepRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SleepinessLevel");

                            b1.HasKey("SleepRecordId");

                            b1.ToTable("SleepRecords");

                            b1.WithOwner()
                                .HasForeignKey("SleepRecordId");

                            b1.HasData(
                                new
                                {
                                    SleepRecordId = new Guid("11111111-1111-1111-1111-111111111111"),
                                    Level = 1
                                },
                                new
                                {
                                    SleepRecordId = new Guid("22222222-2222-2222-2222-222222222222"),
                                    Level = 7
                                });
                        });

                    b.Navigation("PvtResult");

                    b.Navigation("Sleepiness")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
