// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepPvtTracker.Infrastructure.Data;

#nullable disable

namespace SleepPvtTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SleepPvtTracker.Core.Domain.Entities.SleepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SleepRecords");
                });

            modelBuilder.Entity("SleepPvtTracker.Core.Domain.Entities.SleepRecord", b =>
                {
                    b.OwnsOne("SleepPeriod", "SleepPeriod", b1 =>
                        {
                            b1.Property<Guid>("SleepRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Bedtime")
                                .HasColumnType("TEXT")
                                .HasColumnName("Bedtime");

                            b1.Property<DateTime>("WakeUpTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("WakeUpTime");

                            b1.HasKey("SleepRecordId");

                            b1.ToTable("SleepRecords");

                            b1.WithOwner()
                                .HasForeignKey("SleepRecordId");
                        });

                    b.OwnsOne("SleepPvtTracker.Core.Domain.ValueObjects.PvtResult", "PvtResult", b1 =>
                        {
                            b1.Property<Guid>("SleepRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PvtEndTime");

                            b1.Property<int>("ExtraFalseStarts")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PvtExtraFalseStarts");

                            b1.Property<DateTime>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PvtStartTime");

                            b1.Property<string>("Trials")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PvtTrialsJson");

                            b1.HasKey("SleepRecordId");

                            b1.ToTable("SleepRecords");

                            b1.WithOwner()
                                .HasForeignKey("SleepRecordId");
                        });

                    b.OwnsOne("SleepPvtTracker.Core.Domain.ValueObjects.SubjectiveSleepiness", "Sleepiness", b1 =>
                        {
                            b1.Property<Guid>("SleepRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER")
                                .HasColumnName("SleepinessLevel");

                            b1.HasKey("SleepRecordId");

                            b1.ToTable("SleepRecords");

                            b1.WithOwner()
                                .HasForeignKey("SleepRecordId");
                        });

                    b.Navigation("PvtResult");

                    b.Navigation("SleepPeriod")
                        .IsRequired();

                    b.Navigation("Sleepiness")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
